/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as FuentesRouteImport } from './routes/fuentes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as UsRouteImport } from './routes/us'
import { Route as ContratoIdRouteImport } from './routes/contrato.$id'
import { Route as RequisitosCveEntRouteImport } from './routes/requisitos.$cveEnt'
import { Route as ViviendaIdRouteImport } from './routes/vivienda.$id'
import { Route as ZonaCveEntCveMunRouteImport } from './routes/zona.$cveEnt.$cveMun'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const FuentesRoute = FuentesRouteImport.update({
  id: '/fuentes',
  path: '/fuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const UsRoute = UsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoIdRoute = ContratoIdRouteImport.update({
  id: '/contrato/$id',
  path: '/contrato/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitosCveEntRoute = RequisitosCveEntRouteImport.update({
  id: '/requisitos/$cveEnt',
  path: '/requisitos/$cveEnt',
  getParentRoute: () => rootRouteImport,
} as any)
const ViviendaIdRoute = ViviendaIdRouteImport.update({
  id: '/vivienda/$id',
  path: '/vivienda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonaCveEntCveMunRoute = ZonaCveEntCveMunRouteImport.update({
  id: '/zona/$cveEnt/$cveMun',
  path: '/zona/$cveEnt/$cveMun',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/fuentes': typeof FuentesRoute
  '/mapa': typeof MapaRoute
  '/publicar': typeof PublicarRoute
  '/transparency': typeof TransparencyRoute
  '/us': typeof UsRoute
  '/contrato/$id': typeof ContratoIdRoute
  '/requisitos/$cveEnt': typeof RequisitosCveEntRoute
  '/vivienda/$id': typeof ViviendaIdRoute
  '/zona/$cveEnt/$cveMun': typeof ZonaCveEntCveMunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/fuentes': typeof FuentesRoute
  '/mapa': typeof MapaRoute
  '/publicar': typeof PublicarRoute
  '/transparency': typeof TransparencyRoute
  '/us': typeof UsRoute
  '/contrato/$id': typeof ContratoIdRoute
  '/requisitos/$cveEnt': typeof RequisitosCveEntRoute
  '/vivienda/$id': typeof ViviendaIdRoute
  '/zona/$cveEnt/$cveMun': typeof ZonaCveEntCveMunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/fuentes': typeof FuentesRoute
  '/mapa': typeof MapaRoute
  '/publicar': typeof PublicarRoute
  '/transparency': typeof TransparencyRoute
  '/us': typeof UsRoute
  '/contrato/$id': typeof ContratoIdRoute
  '/requisitos/$cveEnt': typeof RequisitosCveEntRoute
  '/vivienda/$id': typeof ViviendaIdRoute
  '/zona/$cveEnt/$cveMun': typeof ZonaCveEntCveMunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changes'
    | '/fuentes'
    | '/mapa'
    | '/publicar'
    | '/transparency'
    | '/us'
    | '/contrato/$id'
    | '/requisitos/$cveEnt'
    | '/vivienda/$id'
    | '/zona/$cveEnt/$cveMun'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changes'
    | '/fuentes'
    | '/mapa'
    | '/publicar'
    | '/transparency'
    | '/us'
    | '/contrato/$id'
    | '/requisitos/$cveEnt'
    | '/vivienda/$id'
    | '/zona/$cveEnt/$cveMun'
  id:
    | '__root__'
    | '/'
    | '/changes'
    | '/fuentes'
    | '/mapa'
    | '/publicar'
    | '/transparency'
    | '/us'
    | '/contrato/$id'
    | '/requisitos/$cveEnt'
    | '/vivienda/$id'
    | '/zona/$cveEnt/$cveMun'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangesRoute: typeof ChangesRoute
  FuentesRoute: typeof FuentesRoute
  MapaRoute: typeof MapaRoute
  PublicarRoute: typeof PublicarRoute
  TransparencyRoute: typeof TransparencyRoute
  UsRoute: typeof UsRoute
  ContratoIdRoute: typeof ContratoIdRoute
  RequisitosCveEntRoute: typeof RequisitosCveEntRoute
  ViviendaIdRoute: typeof ViviendaIdRoute
  ZonaCveEntCveMunRoute: typeof ZonaCveEntCveMunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuentes': {
      id: '/fuentes'
      path: '/fuentes'
      fullPath: '/fuentes'
      preLoaderRoute: typeof FuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us': {
      id: '/us'
      path: '/us'
      fullPath: '/us'
      preLoaderRoute: typeof UsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato/$id': {
      id: '/contrato/$id'
      path: '/contrato/$id'
      fullPath: '/contrato/$id'
      preLoaderRoute: typeof ContratoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitos/$cveEnt': {
      id: '/requisitos/$cveEnt'
      path: '/requisitos/$cveEnt'
      fullPath: '/requisitos/$cveEnt'
      preLoaderRoute: typeof RequisitosCveEntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vivienda/$id': {
      id: '/vivienda/$id'
      path: '/vivienda/$id'
      fullPath: '/vivienda/$id'
      preLoaderRoute: typeof ViviendaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona/$cveEnt/$cveMun': {
      id: '/zona/$cveEnt/$cveMun'
      path: '/zona/$cveEnt/$cveMun'
      fullPath: '/zona/$cveEnt/$cveMun'
      preLoaderRoute: typeof ZonaCveEntCveMunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangesRoute: ChangesRoute,
  FuentesRoute: FuentesRoute,
  MapaRoute: MapaRoute,
  PublicarRoute: PublicarRoute,
  TransparencyRoute: TransparencyRoute,
  UsRoute: UsRoute,
  ContratoIdRoute: ContratoIdRoute,
  RequisitosCveEntRoute: RequisitosCveEntRoute,
  ViviendaIdRoute: ViviendaIdRoute,
  ZonaCveEntCveMunRoute: ZonaCveEntCveMunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
